name: Fluxo integração contínua - Valentina C. Prado PT302539X

on:
  push:
    branches: [ "main" ]
    paths:
      - 'semana-13-aula-main/semana-13-aula-main/*'
      - '.github/workflows/integracao_continua.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'semana-13-aula-main/semana-13-aula-main/*'
      - '.github/workflows/integracao_continua.yml'

env:
  PYTHON_VERSION: "3.9"

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Instalar dependências
      run: |
       pip install pytest==6.2.5 pylint==2.12.2 pytest-cov==2.12.1
    - uses: actions/checkout@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Verificação de sintaxe
      run: |
            set -euo pipefail
            rc=0
            files=(
              "semana-13-aula-main/semana-13-aula-main/aluno.py"
              "semana-13-aula-main/semana-13-aula-main/main.py"
              "semana-13-aula-main/semana-13-aula-main/testes.py"
              "semana-13-aula-main/semana-13-aula-main/turma.py"
            )
            for f in "${files[@]}"; do
              echo "Linting $f"
              pylint --disable=W0311,R0903 "$f" || rc=1
             
            done
            exit $rc

    - name: Realizar testes e exibir cobertura
      run: |
        pytest semana-13-aula-main/semana-13-aula-main --cov=semana-13-aula-main/semana-13-aula-main
